apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-autos
  # namespace: rob-wing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-autos
  template:
    metadata:
      labels:
        app: simple-autos
    spec:
      containers:
        - name: autos
          image: registry.gitlab.galvanize.com/cohorts/ent/sf/cse-rosa/cse-rosa-2025-02-24/student-work/rob-wing/simple-autos-rosa:latest
          ports:
            - containerPort: 8080
          env:
            - name: spring.profiles.active
              value: "default"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-host
                  optional: false
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-port
                  optional: false
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-name
                  optional: false
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-user
                  optional: false
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-password
                  optional: false
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
