apiVersion: v1
kind: Service
metadata:
  name: animal-shelter-for-rosa-cf
spec:
  selector:
    app: animal-shelter-for-rosa-cf  # Matches the label in deploy.yaml
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer