kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: animal-shelter
spec:
  to:
    kind: Service
    name: animal-shelter
    weight: 100
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  wildcardPolicy: None

