apiVersion: v1
kind: Service
metadata:
  name: animal-shelter
  # namespace: rob-wing
spec:
  selector:
    app: animal-shelter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  type: ClusterIP