apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: animal-shelter-for-rosa-cf-db-credentials-eso
  namespace: cse-cody-ferguson
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: animal-shelter-for-rosa-cf-aws-secrets-irsa # Replace with the name of a SecretStore
    kind: SecretStore
  target:
    template:
      engineVersion: v2
      data:
        DB_HOST: "{{ index . `db-host` }}"
        DB_PORT: "{{ index . `db-port` }}"
        DB_NAME: "{{ index . `db-name` }}"
        DB_USER: "{{ index . `db-user` }}" 
        DB_PWD: "{{ index . `db-password` }}"  
        SPRING_PROFILES_ACTIVE: "default" 
    name: animal-shelter-for-rosa-cf-db-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: animals-database-credentials