apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: animal-shelter-for-rosa-cf-hpa
  namespace: cse-cody-ferguson
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: animal-shelter-for-rosa-cf-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50