apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: animal-shelter-for-rosa-cf-aws-secrets-irsa
  namespace: cse-cody-ferguson
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2 # Replace with the AWS region where your secrets are stored if it is not in us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: animal-shelter-for-rosa-cf-asm-access