INSERT INTO animals (birthdate, description, name, type) VALUES ('2016-06-26 22:21:59', 'A calm and affectionate pet with a soft coat.', 'Rex', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2018-08-09 00:44:26', 'Loves long walks and enjoys fetching balls.', 'Rex', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2020-05-16 03:02:37', 'Loyal and protective, always by your side.', 'Max', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2016-06-30 03:16:22', 'Known for its intelligence and loyalty.', 'Toby', 'HORSE');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2016-07-24 13:33:49', 'A playful and energetic companion.', 'Max', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2016-02-26 19:37:21', 'Has a vibrant personality and loves attention.', 'Bella', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2020-03-20 16:03:39', 'Has a vibrant personality and loves attention.', 'Jack', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2024-08-02 19:43:35', 'Enjoys climbing and perching on high places.', 'Rosie', 'HORSE');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2017-02-12 03:18:24', 'Has a vibrant personality and loves attention.', 'Molly', 'DOG');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2019-09-05 14:15:29', 'Enjoys climbing and perching on high places.', 'Toby', 'CAT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2016-12-04 12:09:47', 'Loves long walks and enjoys fetching balls.', 'Bailey', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2024-08-19 05:47:36', 'Strong and graceful, loves running in open fields.', 'Daisy', 'RABBIT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2019-02-18 07:37:57', 'A curious and gentle animal with soft fur.', 'Ginger', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2024-06-08 07:43:40', 'A curious and gentle animal with soft fur.', 'Finn', 'RABBIT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2015-07-10 06:00:30', 'Loyal and protective, always by your side.', 'Luna', 'RABBIT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2018-08-05 01:34:28', 'Enjoys chirping in the morning and loves seeds.', 'Rosie', 'RABBIT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2022-03-28 00:36:21', 'Loyal and protective, always by your side.', 'Charlie', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2018-08-29 22:13:26', 'Enjoys chirping in the morning and loves seeds.', 'Cooper', 'BIRD');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2016-10-17 19:00:06', 'A playful and energetic companion.', 'Peanut', 'RABBIT');
INSERT INTO animals (birthdate, description, name, type) VALUES ('2018-09-12 16:42:55', 'A playful and energetic companion.', 'Rocky', 'RABBIT');